---
- name: Install any necessary dependencies [RedHat/CentOS]
  yum:
    name: curl
    state: present

- name: Add InfluxData repository file [RHEL/CentOS]
  template:
    src: etc/yum.repos.d/influxdata.repo.j2
    dest: /etc/yum.repos.d/influxdata.repo
    force: yes
    backup: yes

- name: Install InfluxDB packages [RHEL/CentOS]
  yum:
    name: influxdb
    state: present
