---
- include_tasks: install-debian-download.yml
  when: influxdb_install_method == "download" and ansible_os_family == "Debian"

- include_tasks: install-debian.yml
  when: influxdb_install_method == "repository" and ansible_os_family == "Debian"

- include_tasks: install-redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: install-debian.yml
  when: ansible_os_family == "Debian"