---
driver:
  name: docker
platforms:
  - name: ansible-role-influxdb-ubuntu-1404
    image: ubuntu:14.04

  - name: ansible-role-influxdb-ubuntu-1604
    image: ubuntu:16.04

  - name: ansible-role-influxdb-centos-7
    image: centos:7

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
